version: '3.9'
services:
  redis:
    image: redis:alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - '6379:6379'
    env_file:
      - .env